### PR TITLE
Remove jQuery dependency from Modal component

### PR DESCRIPTION
**Pull request by restlessdesign**
Doesn’t look like this is actually needed (the docs agree)

### CODE REVIEW

**Comment by ariabuckles** [comment]
Thanks! Looks good to me. Could you sign the Khan Academy CLA by chance? https://khanacademy.org/r/cla

**Comment by restlessdesign** [comment]
Hi @ariabuckles, I tried…but when I submitted the form, this error page was returned.

> The app is currently unreachable.

Happy to sign again once it’s back up!

**Comment by restlessdesign** [comment]
Signed and submitted!

**Comment by ariabuckles** [comment]
Thanks!

**Pull request merged**
