### PR TITLE
Removes petulant verbiage

### PR DESCRIPTION
**Pull request by austinpray**
👮

### CODE REVIEW

**Comment by joelburget** [comment]
I think I'd rather remove / rephrase this sentence. (As the original author) it comes off as petulant.

**Comment by austinpray** [comment]
Delete

>
You should know that I highly recommend not using this mixin. It inevitably leads to inefficient code and janky UX. Not at first - only gradually. You won't really notice until it's too late and BackboneMixin runs the interface you just spent three months on.
>
Anyway, you're your own person - do what you think is right.

Replace with

>
This mixin is deprecated and we do not recommend using it in production.

?

**Comment by joelburget** [comment]
Looks perfect to me!

**Comment by austinpray** [comment]
@joelburget amended the commit to reflect the changes

**Comment by brownhead** [comment]
Whoops, sorry this never got merged!

**Pull request merged**
