### PR TITLE
Lodash support

### PR DESCRIPTION
**Pull request by tarjei**
Hi, I guess there might be other places in the code that will break if I substitute underscore with lodash, but this is the one that hit me.

I haven't done a complete code review of all the components wrt to lodash, but please accept this patch.

T

### CODE REVIEW

**Comment by kevinbarabash** [comment]
We probably want to replace underscore with built functions where possible.

**Comment by tarjei** [comment]
Even better! Butikker until then, is the Pr ok?
7. des. 2015 17.41 skrev "Kevin Barabash" <notifications@github.com>:

**Comment by spicyj** [comment]
Wouldn't this break underscore?

**Comment by tarjei** [comment]
Afaik not: http://underscorejs.org/#value

**Comment by ariabuckles** [comment]
However, unlike lodash, underscore doesn't wrap the returned value of _(). methods unless you use .chain(). I also don't think this is compatible. I think the best approach would be @kevinbarabash's suggestion.

Is this depending on a global underscore? Because we could also fix that to depend on require("underscore"), which should make it compatible with running in an environment that also uses lodash.

**Comment by ariabuckles** [comment]
(Also, the failing build above does seem to be indicative of this: https://travis-ci.org/Khan/react-components/builds/95348153 "TypeError: Object [object Object],[object Object] has no method 'value'")

**Comment by tarjei** [comment]
Ok, I'll come up with a patch that doesn't use underscore :P


With regard to global dependencies, I just made webpack replace underscore
with lodash. Obviously it doesn't always work, but I got a bit further.



2015-12-07 19:44 GMT+01:00 Aria Buckles <notifications@github.com>:

> However, unlike lodash, underscore doesn't wrap the returned value of _().
> methods unless you use .chain(). I also don't think this is compatible. I
> think the best approach would be @kevinbarabash
> <https://github.com/kevinbarabash>'s suggestion.
>
> Is this depending on a global underscore? Because we could also fix that
> to depend on require("underscore"), which should make it compatible with
> running in an environment that also uses lodash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/react-components/pull/51#issuecomment-162620117>.
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by kevinbarabash** [comment]
@tarjei it looks like this changes has been made in another commit.  Sorry for not merging your PR.

**Comment by tarjei** [comment]
Null stress.

**Pull request closed without merging**
